name: bicep-unit-tests
on:
  pull_request:
    branches:
        - main
        - staging
        - dev


jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    environment: ${{github.ref_name == 'main' && 'Production' || github.ref_name == 'staging' && 'Preprod' || 'Dev'}}
    permissions:
        id-token: write
        contents: read
        security-events: write
        issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_FAIL_ON: all 