name: Deploy to Dev

on:
#   push:
#     branches: [Dev]
#   pull_request:
#     branches: [Dev]
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yml
    permissions:
      id-token: write  # Required for Federated Identity Login
      contents: read   # Required for checking out the repo
    with:
      project: MyWebApp
      environment: DevEnvironment
      webapp_name: app-ghpoc1-appservice-dev-test
      parameter_file: ./infra/params-dev.json
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
