name: Deploy AVM Bicep with OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upgrade Azure CLI (optional)
        run: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash


      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep file with parameters (workaround for @ bug)
        run: |
          az deployment sub create \
            --location eastus \
            --template-file main.bicep \
            --parameters \
              rgName="rg-avm-dev" \
              location="eastus"

