# .github/workflows/deploy-devapp.yml

name: Deploy to required Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target deployment environment'
        required: true
        default: DevEnvironment
      webapp_name:
        description: 'Azure App Service name'
        required: true
        default: app-ghpoc1-appservice-dev-test
      parameter_file:
        description: 'Path to Bicep parameter file'
        required: true
        default: ./infra/params-dev.json

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yml
    permissions:
      id-token: write
      contents: read
    with:
      project: MyWebApp
      environment: ${{ github.event.inputs.environment }}
      webapp_name: ${{ github.event.inputs.webapp_name }}
      parameter_file: ${{ github.event.inputs.parameter_file }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
