name: truffle scan
on:
  pull_request:
    branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
        security-events: write
        issues: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --results=verified,unknown